name: Test installer

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
        shell:
          - dash # Minimal `sh` implementation, good for testing POSIX compliance.
          - bash # The most common shell.
          - zsh # The default shell on macOS.
        args:
          - name: bare
            value: ""
          - name: versioned
            value: "-v 0.18.0"
        exclude:
          # Dash is not available on macOS.
          - { os: macos-latest, shell: dash }
          - { os: macos-15-intel, shell: dash }

    name: Test installer (${{ matrix.os }}, ${{ matrix.shell }}, ${{ matrix.args.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install shell
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ${{ matrix.shell }}

      - name: Edit PATH
        run: echo "PATH=$PATH:$HOME/.local/bin" >> "$GITHUB_ENV"

      - name: Run installer
        run: ${{ matrix.shell }} ./installer.sh ${{ matrix.args.value }}

      - run: wasp version
